image: php:8.2

stages:
  - install
  - test

cache:
  paths:
    - vendor/

before_script:
  - apt-get update && apt-get install -y unzip git curl
  - curl -sS https://getcomposer.org/installer | php

install_dependencies:
  stage: install
  script:
    - php composer.phar install
  artifacts:
    paths:
      - vendor/

phpunit_tests:
  stage: test
  script:
    - php composer.phar test